name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: self-hosted
    environment: .env
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install dependencies (verbose)
        run: npm ci --verbose
      - name: Create env file
        run: |
          touch .env
          echo NOTION_TOKEN=${{ secrets.NOTION_TOKEN }} >> .env
          cat .env
      - name: Copy Orienting Directory
        run: rsync -a --delete orienting.sfpc.study/ /var/www/orienting.sfpc.study/html/