name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: .env
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm ci --verbose
        timeout-minutes: 5

      - name: Create env file
        run: |
          touch .env
          echo NOTION_TOKEN=${{ secrets.NOTION_TOKEN }} >> .env
          cat .env

      # - name: Ensure target directory exists
      #   run: mkdir -p /var/www/orienting.sfpc.study/html/

     # - name: Copy Orienting Directory
     #   run: rsync -a --delete orienting.sfpc.study/ /var/www/orienting.sfpc.study/html/
